config/routes.rb
Rails.application.routes.draw do
  namespace :lojista do
    get 'plano/edit'
    patch 'plano/update'
    get 'plano/show'
  end
  namespace :admin do
    get 'setting_perfil/index'
    get 'setting_perfil/edit'
    patch 'setting_perfil/update'
  end
  namespace :lojista do
    get 'produto/index'
    get 'produto/new'
    get 'produto/show'
    post 'produto/create'
    get 'produto/edit'
    patch 'produto/update'
    delete 'produto/destroy'
  end
  namespace :lojista do
    get 'plano_pagamentos/index'
    get 'plano_pagamentos/new'
    get 'plano_pagamentos/edit'
    post 'plano_pagamentos/create'
    patch 'plano_pagamentos/update'
    delete 'plano_pagamentos/destroy'
  end
  namespace :lojista do
    get 'produto_categorias/index'
    get 'produto_categorias/edit'
    get 'produto_categorias/new'
    post 'produto_categorias/create'
    patch 'produto_categorias/update'
    delete 'produto_categorias/destroy'
  end
  namespace :lojista do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
  end
  root 'home#index'
  namespace :lojista do
    get 'panel/visao_geral'
    get 'panel/editar_loja'
    patch 'panel/editar_loja'
    get 'panel/editar_perfil'
    patch 'panel/editar_perfil'
  end
  namespace :admin do
    get 'panel/visao_geral'
  end
  namespace :admin do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
    resources :groups
    resources :permission_flow_actions
    resources :permission_flows
    resources :sub_menus
    resources :menus
    resources :countries do
      resources :states do
        resources :cities do
          resources :bairros do
            resources :ceps
          end
        end
      end
    end
    resources :plataformas do
      resources :plataforma_usuarios, except: :index
    end
    resources :planos
    resources :empresa_seguimentos
    resources :periodos
    resources :empresas do
      resources :empresa_usuarios, except: :index
      resources :produto_categoria, except: [:index, :show]
      resources :plano_pagamentos, except: [:index, :show]
      resources :produtos, except: :index
    end

  end
  get 'home/index'
  get 'home/visualizar_empresa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_menu.rb
#encoding utf-8
#t.references :menu, foreign_key: true
#t.references :sub_menu, foreign_key: true
#t.references :permission_action, foreign_key: true
#t.string :name, null: false
#t.boolean :ajax, null: false, default: true
#t.boolean :active, null: false, default: true
class SubMenu < ApplicationRecord
  #Relacionamentos
  belongs_to :menu
  belongs_to :sub_menu, optional: true
  belongs_to :permission_action
  has_many :permission_flows
  #Validacoes
  validates :name, presence: true, length: {maximum: 255}
  validates :ajax, :active, presence: true, inclusion: {in: [true,false]}
  #CallBack
  #Escopes
end

app/controllers/admin/sub_menus_controller.rb
class Admin::SubMenusController < ApplicationController
  layout 'admin_application'
  before_action :set_sub_menu, only: [:show, :edit, :update, :destroy]
  before_action :all_references, only: [:new, :create, :edit]

  # GET /sub_menus
  # GET /sub_menus.json
  def index
    @sub_menus = SubMenu.all
  end

  # GET /sub_menus/1
  # GET /sub_menus/1.json
  def show
  end

  # GET /sub_menus/new
  def new
    @sub_menu = SubMenu.new
  end

  # GET /sub_menus/1/edit
  def edit
  end

  # POST /sub_menus
  # POST /sub_menus.json
  def create
    @sub_menu = SubMenu.new(sub_menu_params)

    respond_to do |format|
      if @sub_menu.save
        format.html { redirect_to [:admin, @sub_menu], notice: 'Sub menu criado com sucesso.' }
        format.json { render :show, status: :created, location: @sub_menu }
      else
        format.html { render :new }
        format.json { render json: @sub_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_menus/1
  # PATCH/PUT /sub_menus/1.json
  def update
    respond_to do |format|
      if @sub_menu.update(sub_menu_params)
        format.html { redirect_to [:admin, @sub_menu], notice: 'Sub menu atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @sub_menu }
      else
        format.html { render :edit }
        format.json { render json: @sub_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_menus/1
  # DELETE /sub_menus/1.json
  def destroy
    @sub_menu.destroy
    respond_to do |format|
      format.html { redirect_to admin_sub_menus_url, notice: 'Sub menu deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_menu
      @sub_menu = SubMenu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_menu_params
      params.require(:sub_menu).permit(:menu_id, :sub_menu_id, :permission_action_id, :name, :ajax, :active)
    end
end

def all_references
  @menus = Menu.where(active: true)
  @sub_menus = SubMenu.where(active: true)
  @permission_actions = PermissionAction.where(action_link: true)
end

app/helpers/sub_menus_helper.rb
module SubMenusHelper
end

app/views/admin/sub_menus/_form.html.erb
<!-- Modelo Forms -->
</br>
<div class="bg-holder d-none d-lg-block stiviebg-card " style="background-image:url(../assets/img/illustrations/corner-4.png);">
</div>
<%= form_with(model: [:admin, sub_menu], local: true) do |form| %>
  <%= error_messages_for sub_menu %>

  <!-- Inicio Cabeçalho -->
  <div class="card mb-3">
    <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
    </div>
  </div>
  <!-- Fim Cabeçalho -->

  <div class="card mb-3">
    <div class="card-header">
      <h3 class="mb-0"><%=  sub_menu.new_record? ? 'Sub Menu' : 'Editar Sub Menu'  %></h3>
      <h6 class="mb-1 float-right text-primary">Formulário</h6>
      <h3 class="mb-3 col-12 dropdown-divider"></h3>
    </div>
    <div class="card-body bg-light">
      <div class="row">
        <div class="col-12">
          <form>
            <div class="form-group">
              <%= form.label :menu_id %>
              <%= form.select :menu_id , @menus.collect{|menu| [menu.name, menu.id ]}, {include_blank: 'Selecione um menu'},{class:'form-control'} %>
            </div>
            <div class="form-group">
              <%= form.label :sub_menu_id %>
              <%= form.select :sub_menu_id , @sub_menus.collect {|sub_menu| [sub_menu.name, sub_menu.id ]}, {include_blank: 'Selecione um sub-menu'},{class:'form-control'} %>
            </div>
            <div class="form-group">
              <%= form.label :permission_action_id %>
              <%= form.select :permission_action_id , @permission_actions.collect {|action| [action.caminho, action.id ]}, {include_blank: 'Selecione uma action'},{class:'form-control'} %>
            </div>
            <div class="form-group">
              <%= form.label :name, "Nome" %>
              <%= form.text_field :name, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= form.label :ajax, "Ajax" %>
              <%= form.select :ajax, options_for_select([["Sim", true], ["Nao", false]], sub_menu.ajax ),{}, {class:'form-control'} %>
            </div>
            <div class="form-group">
              <%= form.label :active, "Ajax" %>
              <%= form.select :active, options_for_select([["Sim", true], ["Nao", false]], sub_menu.active ),{}, {class:'form-control'} %>
            </div>
          </form>
          <%= form.submit  sub_menu.new_record? ? 'Salvar' : 'Editar', class:'btn btn-primary mb-3'  %>
          <%= link_to 'Voltar', admin_menus_path, class:'btn btn-warning mb-3' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/sub_menus/_index.html.erb
<!-- Modelo Index -->
<br>
<div class="card mb-3">
  <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
  </div>
  <!--/.bg-holder-->

</div>

<div class="card mb-3">

  <div class="card-header">
    <h3 class="mb-0 text-center"> Sub Menus </h3>
    <div class="dropdown-divider mb-3"></div>
    <div class="row align-items-center justify-content-between">
      <div class="col-6 col-sm-auto ml-auto text-right pl-0">
        <div class="d-none" id="purchases-actions">
          <div class="input-group input-group-sm">
            <select class="custom-select cus" aria-label="Bulk actions">
              <option selected="">Bulk actions</option>
              <option value="Refund">Refund</option>
              <option value="Delete">Delete</option>
              <option value="Archive">Archive</option>
            </select>
            <button class="btn btn-falcon-default btn-sm ml-2" type="button">Apply</button>
          </div>
        </div>
        <div class="col-6 col-sm-auto ml-auto text-right pl-0">
          <div>
            <%= link_to new_admin_sub_menu_path, class: "btn btn-primary btn-sm" do %>
              <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ml-1">Novo</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">
      <table class="table table-sm table-dashboard fs--1  border-bottom" data-options='{"responsive":false,"pagingType":"simple","lengthChange":false,"searching":false,"pageLength":8,"columnDefs":[{"targets":[0,6],"orderable":false}],"language":{"info":"_START_ to _END_ Items of _TOTAL_ — <a href=\"#!\" class=\"font-weight-semi-bold\"> view all <span class=\"fas fa-angle-right\" data-fa-transform=\"down-1\"></span> </a>"},"buttons":["copy","excel"]}'>
        <thead class="bg-200 text-900">
        <tr>
          <th class="no-sort pr-1 align-middle data-table-row-bulk-select">
            <div class="custom-control custom-checkbox">
              <input class="custom-control-input checkbox-bulk-select" id="checkbox-bulk-purchases-select" type="checkbox" data-checkbox-body="#purchases" data-checkbox-actions="#purchases-actions" data-checkbox-replaced-element="#dashboard-actions" />
              <label class="" for="checkbox-bulk-purchases-select"></label>
            </div>
          </th>
          <th class="sort pr-1 align-middle">Menu</th>
          <th class="sort pr-1 align-middle">Sub Menu</th>
          <th class="sort pr-1 align-middle">Permission</th>
          <th class="sort pr-1 align-middle">Action</th>
          <th class="sort pr-1 align-middle text-center">Ajax</th>
          <th class="sort pr-1 align-middle text-center">Situação</th>
          <th class="no-sort pr-1 align-middle data-table-row-action"></th>
        </tr>
        </thead>
        <tbody id="purchases">
        <% @sub_menus.each do |sub_menu| %>
          <tr class="btn-reveal-trigger">
            <td class="align-middle">
              <div class="custom-control custom-checkbox">
                <input class="custom-control-input checkbox-bulk-select-target" type="checkbox" id="checkbox-0" />
                <label class="" for="checkbox-0"></label>
              </div>
            </td>
            <th class="align-middle"><%= sub_menu.menu.name %></th>
            <td class="align-middle"><%= sub_menu.name  %></td>
            <td class="align-middle"><%= sub_menu.permission_action.caminho %></td>
            <td class="align-middle"><%= sub_menu.name   %></td>
            <td class="align-middle text-center fs-0"><span class="badge badge rounded-capsule <%= sub_menu.ajax ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= sub_menu.ajax ? 'Sim' : 'Nao' %></span>
            </td>
            <td class="align-middle text-center fs-0"><span class="badge badge rounded-capsule <%= sub_menu.active ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= sub_menu.active ? 'Sim' : 'Nao' %></span>
            </td>
            <td class="align-middle white-space-nowrap">
              <div class="dropdown text-sans-serif">
                <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal mr-3" type="button" id="dropdown0" data-toggle="dropdown" data-boundary="html" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h fs--1"></span></button>
                <div class="dropdown-menu dropdown-menu-right border py-0" aria-labelledby="dropdown0">
                  <%= link_to 'Visualizar', [:admin, sub_menu], class:'dropdown-item text-secondary' %>
                  <div class="bg-white py-2"><%= link_to 'Editar', edit_admin_sub_menu_path(sub_menu), class:'dropdown-item text-warning' %>
                    <div class="dropdown-divider"></div><%= link_to 'Deletar', admin_sub_menu_path(sub_menu), method: :delete, data: { confirm: 'Deseja realmente deletar?' }, class:'dropdown-item text-danger' %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/sub_menus/edit.html.erb
<%= render 'form', sub_menu: @sub_menu %>

app/views/admin/sub_menus/new.html.erb
<%= render 'form', sub_menu: @sub_menu %>

app/views/admin/sub_menus/show.html.erb
</br>

<div class="card mb-3">
  <div class="card-header">
    <h4 class="float-left "><strong> Sub Menu </strong></h4>
    <h5 class=" float-right text-primary  border-sm-bottom border-200"><%=  @sub_menu.menu.name %></h5>
    <h3 class="mb-3 col-12 dropdown-divider"></h3>
    <table class="table table-sm table-bordered ">
      <thead class="thead-light">
      <tr>
        <th>Sub_menu</th>
        <th class=" text-center">Situação</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th class="white-space-nowrap"><%= @sub_menu.name %></th>
        <td class=" text-center"><span class="badge badge rounded-capsule <%= @sub_menu.active ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= @sub_menu.active ? 'Ativado' : 'Desativado' %></span>
      </tr>
      </tbody>
    </table>
  </div>
  <%= link_to 'Voltar',  admin_menus_path, class:'btn btn-sm btn-warning' %>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">

    </div>

  </div>
</div>