config/routes.rb
Rails.application.routes.draw do
  namespace :lojista do
    get 'plano/edit'
    patch 'plano/update'
    get 'plano/show'
  end
  namespace :admin do
    get 'setting_perfil/index'
    get 'setting_perfil/edit'
    patch 'setting_perfil/update'
  end
  namespace :lojista do
    get 'produto/index'
    get 'produto/new'
    get 'produto/show'
    post 'produto/create'
    get 'produto/edit'
    patch 'produto/update'
    delete 'produto/destroy'
  end
  namespace :lojista do
    get 'plano_pagamentos/index'
    get 'plano_pagamentos/new'
    get 'plano_pagamentos/edit'
    post 'plano_pagamentos/create'
    patch 'plano_pagamentos/update'
    delete 'plano_pagamentos/destroy'
  end
  namespace :lojista do
    get 'produto_categorias/index'
    get 'produto_categorias/edit'
    get 'produto_categorias/new'
    post 'produto_categorias/create'
    patch 'produto_categorias/update'
    delete 'produto_categorias/destroy'
  end
  namespace :lojista do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
  end
  root 'home#index'
  namespace :lojista do
    get 'panel/visao_geral'
    get 'panel/editar_loja'
    patch 'panel/editar_loja'
    get 'panel/editar_perfil'
    patch 'panel/editar_perfil'
  end
  namespace :admin do
    get 'panel/visao_geral'
  end
  namespace :admin do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
    resources :groups
    resources :permission_flow_actions
    resources :permission_flows
    resources :sub_menus
    resources :menus
    resources :countries do
      resources :states do
        resources :cities do
          resources :bairros do
            resources :ceps
          end
        end
      end
    end
    resources :plataformas do
      resources :plataforma_usuarios, except: :index
    end
    resources :planos
    resources :empresa_seguimentos
    resources :periodos
    resources :empresas do
      resources :empresa_usuarios, except: :index
      resources :produto_categoria, except: [:index, :show]
      resources :plano_pagamentos, except: [:index, :show]
      resources :produtos, except: :index
    end

  end
  get 'home/index'
  get 'home/visualizar_empresa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plano.rb
#encoding utf-8
#t.references :plataforma, foreign_key: true
#t.string :descricao, null: false
#t.decimal :valor, null: false
#t.integer :qtd_produto, null: false
#t.boolean :ativo, null: false, default: true
class Plano < ApplicationRecord
  #Relacionamento
  belongs_to :plataforma
  has_many :empresas
  #Validacoes
  validates :descricao, presence: true, length: {maximum: 255}
  validates :valor, :qtd_produto, presence: true, numericality: true
  validates :ativo,  inclusion: {in: [true, false]}
  #CallBacks
  #Escopes
  #Metodo de Classe
end

app/controllers/admin/planos_controller.rb
class Admin::PlanosController < ApplicationController
  layout 'admin_application'
  before_action :set_plano, only: [:show, :edit, :update, :destroy]
  before_action :carrega_plataforma

  # GET /planos
  # GET /planos.json
  def index
    @planos = Plano.all
  end

  # GET /planos/1
  # GET /planos/1.json
  def show
  end

  # GET /planos/new
  def new
    @plano = Plano.new
  end

  # GET /planos/1/edit
  def edit
  end

  # POST /planos
  # POST /planos.json
  def create
    @plano = Plano.new(plano_params)

    respond_to do |format|
      if @plano.save
        format.html { redirect_to [:admin, @plano], notice: 'Plano criado com sucesso.' }
        format.json { render :show, status: :created, location: @plano }
      else
        format.html { render :new }
        format.json { render json: @plano.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planos/1
  # PATCH/PUT /planos/1.json
  def update
    respond_to do |format|
      if @plano.update(plano_params)
        format.html { redirect_to [:admin, @plano], notice: 'Plano atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @plano }
      else
        format.html { render :edit }
        format.json { render json: @plano.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planos/1
  # DELETE /planos/1.json
  def destroy
    @plano.destroy
    respond_to do |format|
      format.html { redirect_to admin_planos_url, notice: 'Plano deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_plano
    @plano = Plano.find(params[:id])
  end

  def carrega_plataforma
    @plataformas = Plataforma.all
  end

  # Only allow a list of trusted parameters through.
  def plano_params
    params.require(:plano).permit(:plataforma_id, :descricao, :valor, :qtd_produto, :ativo)
  end
end

app/controllers/lojista/plano_controller.rb
class Lojista::PlanoController < ApplicationController
  layout "lojista_application"
  skip_before_action :usuario_logado
  before_action :empresa_logado
  before_action :set_plano, only: [:update, :edit, :show]
  before_action :carrega_plataforma
  def edit
  end

  def show

  end

  def update
    respond_to do |format|
      if @plano.update(plano_params)
        format.html { redirect_to lojista_plano_edit_path, notice: 'Produto atualizado com sucesso.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  def set_plano
    @plano = @empresa_logado.empresa.plano
  end

  def carrega_plataforma
    @plataforma = @empresa_logado.empresa.plano.plataforma
  end

  def plano_params
      params.require(:plano).permit(:plataforma_id, :descricao, :valor, :qtd_produto, :ativo)
  end
end

app/helpers/lojista/plano_helper.rb
module Lojista::PlanoHelper
end

app/helpers/planos_helper.rb
module PlanosHelper
end

app/views/admin/planos/_form.html.erb
<!-- Modelo Forms -->
</br>
<div class="bg-holder d-none d-lg-block stiviebg-card " style="background-image:url(../assets/img/illustrations/corner-4.png);">
</div>
<%= form_with(model: [:admin, plano], local: true) do |form| %>
  <%= error_messages_for plano %>

  <!-- Inicio Cabeçalho -->
  <div class="card mb-3">
  </div>
  <!-- Fim Cabeçalho -->

  <div class="card mb-3">
    <div class="card-header">
      <h3 class="mb-0"><%=  plano.new_record? ? 'Plano' : 'Editar Plano'  %></h3>
      <h6 class="mb-1 float-right text-primary">Formulário</h6>
      <h3 class="mb-3 col-12 dropdown-divider"></h3>
    </div>
    <div class="card-body bg-light">
      <div class="row">
        <div class="col-12">
          <form>
            <div class="form-group">
              <%= form.label :plataforma_id %>
              <%= form.select :plataforma_id , @plataformas.collect{|plataforma| [plataforma.descricao, plataforma.id ]}, {include_blank: 'Selecione Plataforma'},{class:'form-control'} %>
            </div>
            <div class="form-group">
              <%= form.label :descricao, "Plano" %>
              <%= form.text_field :descricao, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= form.label :valor, "Valor" %>
              <%= form.text_field :valor, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= form.label :qtd_produto, "Produtos" %>
              <%= form.number_field :qtd_produto, class:'form-control'%>
            </div>
            <div class="form-group">
              <%= form.label :ativo, "Ativo" %>
              <%= form.select :ativo, options_for_select([["Sim", true], ["Nao", false]], plano.ativo ),{}, {class:'form-control'} %>
            </div>
          </form>
          <%= form.submit  plano.new_record? ? 'Salvar' : 'Editar', class:'btn btn-primary mb-3'  %>
          <%= link_to 'Voltar', admin_planos_path, class:'btn btn-warning mb-3' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/planos/edit.html.erb
<%= render 'form', plano: @plano %>

app/views/admin/planos/index.html.erb
</br>
<div class="card mb-3">
  <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
  </div>
  <!--/.bg-holder-->
</div>

<div class="card mb-3">

  <div class="card-header">
    <%= link_to admin_plataformas_path, class: "btn btn-secondary btn-sm float-left" do %>
      <span class="fas fa-address-card" data-fa-transform="shrink-3 down-2"></span> <span class="d-none d-sm-inline-block ml-1">Plataforma</span>
    <% end %>
    <h3 class="mb-0 text-center">Planos</h3>
    <div class="dropdown-divider mb-3"></div>
    <div class="row align-items-center justify-content-between">
      <div class="col-6 col-sm-auto ml-auto text-right pl-0">
        <div class="d-none" id="purchases-actions">
          <div class="input-group input-group-sm">
            <select class="custom-select cus" aria-label="Bulk actions">
              <option selected="">Bulk actions</option>
              <option value="Refund">Refund</option>
              <option value="Delete">Delete</option>
              <option value="Archive">Archive</option>
            </select>
            <button class="btn btn-falcon-default btn-sm ml-2" type="button">Apply</button>
          </div>
        </div>
        <div class="col-6 col-sm-auto ml-auto text-right pl-0">
          <div>
            <%= link_to new_admin_plano_path, class: "btn btn-primary btn-sm" do %>
              <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ml-1">Novo</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">
      <table class="table table-sm table-dashboard fs--1 data-table border-bottom" data-options='{"responsive":false,"pagingType":"simple","lengthChange":false,"searching":false,"pageLength":8,"columnDefs":[{"targets":[0,6],"orderable":false}],"language":{"info":"_START_ to _END_ Items of _TOTAL_ — <a href=\"#!\" class=\"font-weight-semi-bold\"> view all <span class=\"fas fa-angle-right\" data-fa-transform=\"down-1\"></span> </a>"},"buttons":["copy","excel"]}'>
        <thead class="bg-200 text-900">
        <tr>
          <th class="no-sort pr-1 align-middle data-table-row-bulk-select">
            <div class="custom-control custom-checkbox">
              <input class="custom-control-input checkbox-bulk-select" id="checkbox-bulk-purchases-select" type="checkbox" data-checkbox-body="#purchases" data-checkbox-actions="#purchases-actions" data-checkbox-replaced-element="#dashboard-actions" />
              <label class="" for="checkbox-bulk-purchases-select"></label>
            </div>
          </th>
          <th class="sort pr-1 align-middle">Plataforma</th>
          <th class="sort pr-1 align-middle text-center">Plano</th>
          <th class="sort pr-1 align-middle text-center">Valor</th>
          <th class="sort pr-1 align-middle text-center">Produtos</th>
          <th class="sort pr-1 align-middle text-center">Situação</th>
          <th class="no-sort pr-1 align-middle data-table-row-action"></th>
        </tr>
        </thead>
        <tbody id="purchases">
        <%  @planos.each do |plano| %>
          <tr class="btn-reveal-trigger">
            <td class="align-middle">
              <div class="custom-control custom-checkbox">
                <input class="custom-control-input checkbox-bulk-select-target" type="checkbox" id="checkbox-0" />
                <label class="" for="checkbox-0"></label>
              </div>
            </td>
            <th class="align-middle"><%= plano.plataforma.descricao %></th>
            <th class="align-middle text-center"><%= plano.descricao%></th>
            <th class="align-middle text-center"><%= plano.valor%></th>
            <th class="align-middle text-center"><%= plano.qtd_produto%></th>
            <th class="align-middle text-center fs-0"><span class="badge badge rounded-capsule <%= plano.ativo ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= plano.ativo ? 'Sim' : 'Nao' %></span>
            </th>
            <td class="align-middle white-space-nowrap">
              <div class="dropdown text-sans-serif">
                <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal mr-3" type="button" id="dropdown0" data-toggle="dropdown" data-boundary="html" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h fs--1"></span></button>
                <div class="dropdown-menu dropdown-menu-right border py-0" aria-labelledby="dropdown0">
                  <div class="bg-white py-2 "><%= link_to 'Visualizar', admin_plano_path(plano), class:'dropdown-item text-secondary' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to 'Editar', edit_admin_plano_path(plano), class:'dropdown-item text-warning' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to 'Deletar', admin_plano_path(plano),  method: :delete, data: { confirm: 'Deseja realmente deletar?' }, class:'dropdown-item text-danger' %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/planos/new.html.erb
<%= render 'form', plano: @plano %>

app/views/admin/planos/show.html.erb
<br/>
<div class="card mb-3">
  <div class="card-header">
    <h4 class="float-left "><strong class="text-primary"> Plano </strong></h4>
    <h5 class=" float-right text-primary  border-sm-bottom border-200"><%= @plano.plataforma.descricao  %></h5>
    <h5 class=" float-right text-primary col-2"> <%=  %></h5>
    <h3 class="mb-3 col-12 dropdown-divider"></h3>
    <table class="table table-sm table-bordered ">
      <thead class="thead-light">
      <tr>
        <th>Plano</th>
        <th>Valor</th>
        <th>Produtos</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th class="white-space-nowrap"><%= @plano.descricao %></th>
        <th class="white-space-nowrap"><%= @plano.valor %></th>
        <th class="white-space-nowrap"><%= @plano.qtd_produto %></th>
      </tr>
      </tbody>
    </table>
  </div>
  <%= link_to 'Voltar',  admin_planos_path, class:'btn btn-sm btn-warning' %>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">

    </div>

  </div>
</div>