config/routes.rb
Rails.application.routes.draw do
  namespace :lojista do
    get 'plano/edit'
    patch 'plano/update'
    get 'plano/show'
  end
  namespace :admin do
    get 'setting_perfil/index'
    get 'setting_perfil/edit'
    patch 'setting_perfil/update'
  end
  namespace :lojista do
    get 'produto/index'
    get 'produto/new'
    get 'produto/show'
    post 'produto/create'
    get 'produto/edit'
    patch 'produto/update'
    delete 'produto/destroy'
  end
  namespace :lojista do
    get 'plano_pagamentos/index'
    get 'plano_pagamentos/new'
    get 'plano_pagamentos/edit'
    post 'plano_pagamentos/create'
    patch 'plano_pagamentos/update'
    delete 'plano_pagamentos/destroy'
  end
  namespace :lojista do
    get 'produto_categorias/index'
    get 'produto_categorias/edit'
    get 'produto_categorias/new'
    post 'produto_categorias/create'
    patch 'produto_categorias/update'
    delete 'produto_categorias/destroy'
  end
  namespace :lojista do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
  end
  root 'home#index'
  namespace :lojista do
    get 'panel/visao_geral'
    get 'panel/editar_loja'
    patch 'panel/editar_loja'
    get 'panel/editar_perfil'
    patch 'panel/editar_perfil'
  end
  namespace :admin do
    get 'panel/visao_geral'
  end
  namespace :admin do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
    resources :groups
    resources :permission_flow_actions
    resources :permission_flows
    resources :sub_menus
    resources :menus
    resources :countries do
      resources :states do
        resources :cities do
          resources :bairros do
            resources :ceps
          end
        end
      end
    end
    resources :plataformas do
      resources :plataforma_usuarios, except: :index
    end
    resources :planos
    resources :empresa_seguimentos
    resources :periodos
    resources :empresas do
      resources :empresa_usuarios, except: :index
      resources :produto_categoria, except: [:index, :show]
      resources :plano_pagamentos, except: [:index, :show]
      resources :produtos, except: :index
    end

  end
  get 'home/index'
  get 'home/visualizar_empresa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/country.rb
#enconding utf-8
#t.string :name, null: false
#t.string :acronym, null: false
#t.boolean :active, null: false, default: true
#t.string :code, null: false
class Country < ApplicationRecord
  #Relacionamentos
  has_many :states
  #Validacoes
  validates :name, presence: true, length: {maximum: 255}
  validates :acronym, presence: true, length: {minimum: 2, maximum: 3}
  validates :code, presence: true, length: {maximum: 255}
  validates :active, presence: true, inclusion: {in: [true, false]}
  #CallBacks
  #Escopes
  #Metodos de Classe
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
  layout 'admin_application'
  before_action :set_country, only: [:show, :edit, :update, :destroy]


  # GET /countries
  # GET /countries.json
  def index
    if params[:query] == ''
      @countries = Country.all
    else
      @countries = Country.where('name LIKE ?', "%#{params[:query]}%")
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @states = @country.states
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to [:admin, @country], notice: 'País criado com sucesso.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to [:admin, @country], notice: 'País atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to admin_countries_url, notice: 'País deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, :acronym, :active, :code)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/admin/countries/_form.html.erb
</br>
<div class="bg-holder d-none d-lg-block stiviebg-card " style="background-image:url(../assets/img/illustrations/corner-4.png);">
</div>
  <%= form_with(model: [:admin, country], local: true) do |form| %>
    <%= error_messages_for country %>

  <!-- Inicio Cabeçalho -->
  <div class="card mb-3">
    <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
    </div>

  </div>
  <!-- Fim Cabeçalho -->

  <div class="card mb-3">
    <div class="card-header">
      <h3 class="mb-0"><%=  country.new_record? ? 'Novo País' : 'Editar País'  %></h3>
      <h6 class="mb-1 float-right text-primary">Formulário</h6>
      <h3 class="mb-3 col-12 dropdown-divider"></h3>
    </div>
    <div class="card-body bg-light">
      <div class="row">
        <div class="col-12">
          <form>
            <div class="form-group">
              <%= form.label :name, "País" %>
              <%= form.text_field :name, class:'form-control'%>
              <small class="text-muted">Nome do País</small>
            </div>
            <div class="form-group">
              <%= form.label :acronym, "Sigla" %>
              <%= form.text_field :acronym, class:'form-control'%>
              <small class="text-muted">Sigla do País</small>
            </div>
            <div class="form-group">
              <%= form.label :code, "Código" %>
              <%= form.text_field :code, class:'form-control'%>
              <small class="text-muted">Código do País</small>
            </div>
            <div class="form-group">
              <%= form.label :active, "Ativar" %>
              <%= form.select :active, options_for_select([["Sim", true], ["Nao", false]], country.active ),{}, {class:'form-control'} %>
              <small class="text-muted">Ativar ou Desativar</small>
            </div>
          </form>
          <%= form.submit  country.new_record? ? 'Salvar' : 'Editar', class:'btn btn-primary mb-3'  %>
          <%= link_to 'Voltar', admin_countries_path, class:'btn btn-warning mb-3' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/countries/edit.html.erb
<%= render 'form', country: @country %>

app/views/admin/countries/index.html.erb
</br>
<div class="card mb-3">
  <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
  </div>
  <!--/.bg-holder-->
</div>

<div class="card mb-3">

  <div class="card-header">
    <h3 class="mb-0 text-center"> Países (<%= Country.count%>)</h3>
    <div class="dropdown-divider mb-3"></div>
    <%= form_tag admin_countries_path, method: :get do %>
      <div class="input-group mb-3">
        <%= text_field_tag :query, params[:query], class:'form-control', placeholder:'País...' %>
        <%= submit_tag  'Buscar' , name: nil, class:'btn btn-falcon-info mr-1 mb-1' %>
      </div>
    <% end %>
    <div class="row align-items-center justify-content-between">
      <div class="col-6 col-sm-auto ml-auto text-right pl-0">
        <div class="d-none" id="purchases-actions">
          <div class="input-group input-group-sm">
            <select class="custom-select cus" aria-label="Bulk actions">
              <option selected="">Bulk actions</option>
              <option value="Refund">Refund</option>
              <option value="Delete">Delete</option>
              <option value="Archive">Archive</option>
            </select>
            <button class="btn btn-falcon-default btn-sm ml-2" type="button">Apply</button>
          </div>
        </div>
        <div class="col-6 col-sm-auto ml-auto text-right pl-0">
          <div>
            <%= link_to new_admin_country_path, class: "btn btn-sm btn-primary" do %>
              <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ml-1 bg-pr">Novo</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">
      <table class="table table-sm table-dashboard fs--1 data-table border-bottom" data-options='{"responsive":false,"pagingType":"simple","lengthChange":false,"searching":false,"pageLength":8,"columnDefs":[{"targets":[0,6],"orderable":false}],"language":{"info":"_START_ to _END_ Items of _TOTAL_ — <a href=\"#!\" class=\"font-weight-semi-bold\"> view all <span class=\"fas fa-angle-right\" data-fa-transform=\"down-1\"></span> </a>"},"buttons":["copy","excel"]}'>
        <thead class="bg-200 text-900">
        <tr>
          <th class="no-sort pr-1 align-middle data-table-row-bulk-select">
            <div class="custom-control custom-checkbox">
              <input class="custom-control-input checkbox-bulk-select" id="checkbox-bulk-purchases-select" type="checkbox" data-checkbox-body="#purchases" data-checkbox-actions="#purchases-actions" data-checkbox-replaced-element="#dashboard-actions" />
              <label class="" for="checkbox-bulk-purchases-select"></label>
            </div>
          </th>
          <th class="sort pr-1 align-middle">País</th>
          <th class="sort pr-1 align-middle">Sigla</th>
          <th class="sort pr-1 align-middle">Código</th>
          <th class="sort pr-1 align-middle text-center">Situação</th>
          <th class="no-sort pr-1 align-middle data-table-row-action"></th>
        </tr>
        </thead>
        <tbody id="purchases">
        <% @countries.each do |country| %>
          <tr class="btn-reveal-trigger">
            <td class="align-middle">
              <div class="custom-control custom-checkbox">
                <input class="custom-control-input checkbox-bulk-select-target" type="checkbox" id="checkbox-0" />
                <label class="" for="checkbox-0"></label>
              </div>
            </td>
            <th class="align-middle"><%= country.name%></th>
            <th class="align-middle"><%= country.acronym %></th>
            <th class="align-middle"><%= country.code %></th>
            <td class="align-middle text-center fs-0"><span class="badge badge rounded-capsule <%= country.active ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= country.active ? 'Ativado' : 'Desativado' %></span>
            </td>
            <td class="align-middle white-space-nowrap">
              <div class="dropdown text-sans-serif">
                <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal mr-3" type="button" id="dropdown0" data-toggle="dropdown" data-boundary="html" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h fs--1"></span></button>
                <div class="dropdown-menu dropdown-menu-right border py-0" aria-labelledby="dropdown0">
                  <%= link_to 'Visualizar', admin_country_path(country), class:'dropdown-item text-secondary' %>
                  <div class="bg-white py-2"><%= link_to 'Editar', edit_admin_country_path(country), class:'dropdown-item text-warning' %>
                    <div class="dropdown-divider"></div><%= link_to 'Deletar', admin_country_path(country),  method: :delete, data: { confirm: 'Deseja realmente deletar?' }, class:'dropdown-item text-danger' %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/countries/new.html.erb
<%= render 'form', country: @country %>

app/views/admin/countries/show.html.erb
</br>
<div class="card mb-3">
  <div class="card-header">
    <h4 class="float-left "><strong class="text-primary"> País </strong></h4>
    <h5 class=" float-right text-primary  border-sm-bottom border-200"><%= @country.name %></h5>
    <h3 class="mb-3 col-12 dropdown-divider"></h3>
    <table class="table table-sm table-bordered ">
      <thead class="thead-light">
      <tr>
        <th>Nome</th>
        <th>Código</th>
        <th>Sigla</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th class="white-space-nowrap"><%= @country.name %></th>
        <th class="white-space-nowrap"><%= @country.code %></th>
        <th class="white-space-nowrap"><%= @country.acronym %></th>
      </tr>
      </tbody>
    </table>
  </div>
  <%= link_to 'Voltar', admin_countries_path  , class:'btn btn-sm btn-warning' %>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">

    </div>

  </div>
</div>

<%= render 'admin/states/index' %>