config/routes.rb
Rails.application.routes.draw do
  namespace :lojista do
    get 'plano/edit'
    patch 'plano/update'
    get 'plano/show'
  end
  namespace :admin do
    get 'setting_perfil/index'
    get 'setting_perfil/edit'
    patch 'setting_perfil/update'
  end
  namespace :lojista do
    get 'produto/index'
    get 'produto/new'
    get 'produto/show'
    post 'produto/create'
    get 'produto/edit'
    patch 'produto/update'
    delete 'produto/destroy'
  end
  namespace :lojista do
    get 'plano_pagamentos/index'
    get 'plano_pagamentos/new'
    get 'plano_pagamentos/edit'
    post 'plano_pagamentos/create'
    patch 'plano_pagamentos/update'
    delete 'plano_pagamentos/destroy'
  end
  namespace :lojista do
    get 'produto_categorias/index'
    get 'produto_categorias/edit'
    get 'produto_categorias/new'
    post 'produto_categorias/create'
    patch 'produto_categorias/update'
    delete 'produto_categorias/destroy'
  end
  namespace :lojista do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
  end
  root 'home#index'
  namespace :lojista do
    get 'panel/visao_geral'
    get 'panel/editar_loja'
    patch 'panel/editar_loja'
    get 'panel/editar_perfil'
    patch 'panel/editar_perfil'
  end
  namespace :admin do
    get 'panel/visao_geral'
  end
  namespace :admin do
    root 'auth#autenticar'
    get 'auth/autenticar'
    post 'auth/autenticar'
    get 'auth/sair'
    resources :groups
    resources :permission_flow_actions
    resources :permission_flows
    resources :sub_menus
    resources :menus
    resources :countries do
      resources :states do
        resources :cities do
          resources :bairros do
            resources :ceps
          end
        end
      end
    end
    resources :plataformas do
      resources :plataforma_usuarios, except: :index
    end
    resources :planos
    resources :empresa_seguimentos
    resources :periodos
    resources :empresas do
      resources :empresa_usuarios, except: :index
      resources :produto_categoria, except: [:index, :show]
      resources :plano_pagamentos, except: [:index, :show]
      resources :produtos, except: :index
    end

  end
  get 'home/index'
  get 'home/visualizar_empresa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/state.rb
#encoding utf-8
# t.references :country, foreign_key: true
#t.string :code, null: false
#t.string :name, null: false
#t.string :acronym, null: false
#t.boolean :active, null: false, default: true
class State < ApplicationRecord
  #Relacionamnetos
  belongs_to :country
  has_many :cities
  #Validates
  validates :name, presence: true, length: {maximum: 255}
  validates :code, presence: true, length: {maximum: 255}
  validates :acronym, presence: true, length: {minimum: 2, maximum: 3}
  validates :active, presence: true, inclusion: {in: [true, false]}
  #CallBacks
  #Escopes
  #Metodo de Classe
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  layout 'admin_application'
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  before_action :origem_definido
  before_action :carregar_paises
  # GET /states/1
  # GET /states/1.json
  def show
    @cities = @state.cities.order(:name)
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to admin_country_path(@country, @state), notice: 'Estado criado com sucesso.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to admin_country_path(@country, @state), notice: 'Estado atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to admin_country_path(@country, @state), notice: 'Estado deletetado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

  def carregar_paises
    @countries = Country.where(active: true)
  end
  def origem_definido
    #DEF Pais Estado
    @country = Country.find(params[:country_id])
  end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:country_id, :code, :name, :acronym, :active)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/admin/states/_form.html.erb
<div class="bg-holder d-none d-lg-block stiviebg-card " style="background-image:url(../assets/img/illustrations/corner-4.png);">
</div>
<%= form_with(model: [:admin, @country, state] , local: true) do |form| %>
  <%= error_messages_for state %>

  <!-- Inicio Cabeçalho -->
  <div class="card mb-3">
    <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
    </div>

  </div>
  <!-- Fim Cabeçalho -->

  <div class="card mb-3">
    <div class="card-header">
      <h3 class="mb-0"><%=  state.new_record? ? 'Novo Estado' : 'Editar Estado'  %></h3>
      <h6 class="mb-1 float-right text-primary">Formulário</h6>
      <h3 class="mb-3 col-12 dropdown-divider"></h3>
    </div>
    <div class="card-body bg-light">
      <div class="row">
        <div class="col-12">
          <form>
            <div class="field mb-1">
              <%= form.label :country_id,("País #{@country.name}"), class:' font-weight-extra-bold float-right text-primary', style:'font-size: 20px;' %>
              <%= form.hidden_field :country_id, value: @country.id %>
            </div>
            <div class="form-group">
              <%= form.label :name, "Estado" %>
              <%= form.text_field :name, class:'form-control'%>
              <small class="text-muted">Nome do Estado</small>
            </div>
            <div class="form-group">
              <%= form.label :acronym, "Sigla" %>
              <%= form.text_field :acronym, class:'form-control'%>
              <small class="text-muted">Sigla do Estado (duas letras)</small>
            </div>
            <div class="form-group">
              <%= form.label :code, "Código" %>
              <%= form.text_field :code, class:'form-control'%>
              <small class="text-muted">Código do Estado</small>
            </div>
            <div class="form-group">
              <%= form.label :active, "Ativar" %>
              <%= form.select :active, options_for_select([["Sim", true], ["Nao", false]], state.active ),{}, {class:'form-control'} %>
              <small class="text-muted">Ativado ou Desativado</small>
            </div>
          </form>
          <%= form.submit  state.new_record? ? 'Salvar' : 'Editar', class:'btn btn-primary mb-3'  %>
          <%= link_to 'Voltar', admin_country_path(@country, state), class:'btn btn-warning mb-3' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/states/_index.html.erb
</br>
<div class="card mb-3">
  <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(../assets/img/illustrations/corner-4.png);">
  </div>
  <!--/.bg-holder-->
</div>

<div class="card mb-3">

  <div class="card-header">
    <h3 class="mb-0 text-center"> Estados </h3>
    <div class="dropdown-divider mb-3"></div>
    <div class="row align-items-center justify-content-between">
      <div class="col-6 col-sm-auto ml-auto text-right pl-0">
        <div class="d-none" id="purchases-actions">
          <div class="input-group input-group-sm">
            <select class="custom-select cus" aria-label="Bulk actions">
              <option selected="">Bulk actions</option>
              <option value="Refund">Refund</option>
              <option value="Delete">Delete</option>
              <option value="Archive">Archive</option>
            </select>
            <button class="btn btn-falcon-default btn-sm ml-2" type="button">Apply</button>
          </div>
        </div>
        <div class="col-6 col-sm-auto ml-auto text-right pl-0">
          <div>
            <%= link_to new_admin_country_state_path(@country), class: "btn btn-primary btn-sm" do %>
              <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span><span class="d-none d-sm-inline-block ml-1">Novo</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">
      <table class="table table-sm table-dashboard fs--1 data-table border-bottom" data-options='{"responsive":false,"pagingType":"simple","lengthChange":false,"searching":false,"pageLength":8,"columnDefs":[{"targets":[0,6],"orderable":false}],"language":{"info":"_START_ to _END_ Items of _TOTAL_ — <a href=\"#!\" class=\"font-weight-semi-bold\"> view all <span class=\"fas fa-angle-right\" data-fa-transform=\"down-1\"></span> </a>"},"buttons":["copy","excel"]}'>
        <thead class="bg-200 text-900">
        <tr>
          <th class="no-sort pr-1 align-middle data-table-row-bulk-select">
            <div class="custom-control custom-checkbox">
              <input class="custom-control-input checkbox-bulk-select" id="checkbox-bulk-purchases-select" type="checkbox" data-checkbox-body="#purchases" data-checkbox-actions="#purchases-actions" data-checkbox-replaced-element="#dashboard-actions" />
              <label class="" for="checkbox-bulk-purchases-select"></label>
            </div>
          </th>
          <th class="sort pr-1 align-middle text-center">Estado</th>
          <th class="sort pr-1 align-middle text-center">Sigla</th>
          <th class="sort pr-1 align-middle text-center">Situação</th>
          <th class="no-sort pr-1 align-middle data-table-row-action"></th>
        </tr>
        </thead>
        <tbody id="purchases">
        <% @states.each do |state| %>
          <tr class="btn-reveal-trigger">
            <td class="align-middle">
              <div class="custom-control custom-checkbox">
                <input class="custom-control-input checkbox-bulk-select-target" type="checkbox" id="checkbox-0" />
                <label class="" for="checkbox-0"></label>
              </div>
            </td>
            <th class="align-middle text-center"><%= state.name%></th>
            <th class="align-middle text-center"><%= state.acronym %></th>
            <td class="align-middle text-center fs-0"><span class="badge badge rounded-capsule <%= state.active ? 'badge-soft-success' : 'badge-soft-danger'%>"><%= state.active ? 'Ativado' : 'Desativado' %></span>
            </td>
            <td class="align-middle white-space-nowrap">
              <div class="dropdown text-sans-serif">
                <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal mr-3" type="button" id="dropdown0" data-toggle="dropdown" data-boundary="html" aria-haspopup="true" aria-expanded="false"><span class="fas fa-ellipsis-h fs--1"></span></button>
                <div class="dropdown-menu dropdown-menu-right border py-0" aria-labelledby="dropdown0">
                  <div class="bg-white py-2 "><%= link_to 'Visualizar', admin_country_state_path(@country, state), class:'dropdown-item text-secondary' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to 'Editar', edit_admin_country_state_path(@country, state), class:'dropdown-item text-warning' %>
                    <div class="dropdown-divider"></div>
                    <%= link_to 'Deletar', admin_country_state_path(@country, state),  method: :delete, data: { confirm: 'Deseja realmente deletar?' }, class:'dropdown-item text-danger' %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/states/edit.html.erb
<%= render 'form', state: @state %>

app/views/admin/states/new.html.erb
<%= render 'form', state: @state %>

app/views/admin/states/show.html.erb
</br>
<div class="card mb-3">
  <div class="card-header">
    <h4 class="float-left "><strong class="text-primary"> Estado </strong></h4>
    <h5 class=" float-right text-primary  border-sm-bottom border-200"><%= @state.country.name %></h5>
    <h3 class="mb-3 col-12 dropdown-divider"></h3>
    <table class="table table-sm table-bordered ">
      <thead class="thead-light">
      <tr>
        <th>Estado</th>
        <th>Código</th>
        <th>Sigla</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th class="white-space-nowrap"><%= @state.name %></th>
        <th class="white-space-nowrap"><%= @state.code %></th>
        <th class="white-space-nowrap"><%= @state.acronym %></th>
      </tr>
      </tbody>
    </table>
  </div>
  <%= link_to 'Voltar',  admin_country_path(@state.country_id), class:'btn btn-sm btn-warning' %>
  <div class="card-body px-0 pt-0">
    <div class="dashboard-data-table">

    </div>

  </div>
</div>


<%= render 'admin/cities/index' %>